function launchCommand(a,d){var b=!1;ZmPluginInst.host||new ZmPluginInst;if(ZmPluginInst.host){var e=getRefreshedStatus;switch(a){case "workflow":case "incomingchanges":case "repobrowser":case "status":case "reveal":e=issueCommandNoRefresh;break;case "resolve-links":"PHXS"!==ZmPluginInst.host.hostAppCode&&("ILST"!==ZmPluginInst.host.hostAppCode&&"PHSP"!==ZmPluginInst.host.hostAppCode&&"AEFT"!==ZmPluginInst.host.hostAppCode&&"IDSN"!==ZmPluginInst.host.hostAppCode&&"PPRO"!==ZmPluginInst.host.hostAppCode)&&
(b=!0)}"workflow"==a||"repobrowser"==a?issueCommand(a,null,null):!0==b?showAlert(resourceBundle.UNSUPPORTED_ACTION):ZmPluginInst.host.getFilePath(a,e,{_isRefresh:d})}else showAlert(resourceBundle.INVALID_HOST)}function launchSearch(){var a=jQuery("#searchInput").val();a&&sendCommandRequest(getCommandParam("uberSearch",{searchString:a}),null)}
function sendCommandRequest(a,d){try{jQuery.post("http://127.0.0.1:7770/webmin/jsp/process/htmlPluginForker.jsp",a,function(b){var f,c;try{callTimer(),f=b.getElementsByTagName("status").item(0).getAttribute("flag"),c=b.getElementsByTagName("status").item(0).getAttribute("errorMsg"),"true"===f?d&&d(a):c?showAlert(c):showAlert(resourceBundle.REQUEST_NOT_COMPLETE_ERR)}catch(g){showAlert(resourceBundle.INVALID_DATA_ERR+g)}}).fail=function(){showAlert(resourceBundle.REQUEST_FAILED)}}catch(b){showAlert(resourceBundle.REQUEST_SEND_ERR+
b)}}function showAlert(a){evalScript("$._ext.showAlert( '"+a+"' )")}var timer;function setTimer(){timer=setTimeout(function(){launchCommand("refresh","true")},15E3)}function callTimer(){clearTimer();setTimer()}function clearTimer(){timer&&clearTimeout(timer)}
function getRefreshedStatus(a,d,b){try{var e,f=jQuery.post("http://127.0.0.1:7770/webmin/jsp/status/getfilestatusbitsetPlugin.jsp",{path:d,force:!0,adobe:!0},function(a){a=a.getElementsByTagName("status").item(0);var b=a.getAttribute("userName"),c=a.getAttribute("server");setUserDtls(b,c);d&&(e={code:a.getAttribute("code"),bitset:a.getAttribute("bitset")})});f.fail=function(a,b,c){showAlert(resourceBundle.ERROR+f.status+"\n"+resourceBundle.ERROR_THROWN+c)};f.always=function(){e&&(b&&b._isRefresh&&
"true"===b._isRefresh?refreshStatus(e):"loadSettings"!=a&&"saveSettings"!=a&&executeActionOnRefresh(a,e,d));"loadSettings"==a?readUserSettings(updatePropUI,null,null):"saveSettings"==a&&saveProperty()};d||refreshBlankFileStatus()}catch(c){showAlert(resourceBundle.ERROR+c)}}
function executeActionOnRefresh(a,d,b){var e=d.code;0>e&&(d.code=-e);var f=d.bitset,c=isVersioned(e),g=!1,h=!1,f=isModified(e,f);!0===c?(g=ADDED.getStatusCode()==e,h=!1):h=isNonWc(e);if(ZmPluginInst.host&&!1===ZmPluginInst.host.isDefault&&b)switch(a){case "checkIn":ZmPluginInst.host.saveDocument(!0===c||!0===g||!1===h?"commit":"import",retrieveSettings,{remotepath:b,checkModified:!0,modifiedFlag:f});break;case "smartCopy":if(!0===c)try{var k=updateModStatus(e,d.bitset);issueCommand(a,null,{remotepath:b,
modifiedFlag:k&&!0===k?1:0})}catch(l){showAlert(l)}else showAlert(resourceBundle.SMART_CPY_UNVERSIONED_ERR);break;case "update":!0!==c||g&&!0===g?showAlert(resourceBundle.UPDATE_UNVERSIONED_ERR):ZmPluginInst.host.saveDocument(a,closeCurrentDocument,{remotepath:b});break;case "lock":case "unlock":!0!==c||g&&!0===g?showAlert(resourceBundle.LOCK_UNLOCK_UNVERSIONED_ERR):issueCommand(a,null,{remotepath:b});break;case "revertdata":case "revertrenamed":case "revertmove":case "revertadd":case "revertall":!0!==
c?showAlert(resourceBundle.REVERT_UNVERSIONED_ERR):ZmPluginInst.host.saveDocument(a,closeCurrentDocument,{remotepath:b});break;case "quickChkIn":ZmPluginInst.host.saveDocument(!0===c||!0===g?"quick_commit":"quick_import",retrieveSettings,{remotepath:b,checkModified:!0,modifiedFlag:f});break;case "asset_browser":!0!==c||g&&!0===g?issueCommand(a,null,{remotepath:b,versionFlag:0}):issueCommand(a,null,{remotepath:b,versionFlag:1});break;case "resolve-links":!0!==c||g&&!0===g?showAlert(resourceBundle.RESOLVE_LINKS_UNVERSIONED_ERR):
!0==f?issueResolveLinks(a,"false",{parentFilePath:b}):ZmPluginInst.host.isChangesSaved(a,issueResolveLinks,{parentFilePath:b});break;default:showAlert(resourceBundle.UNKNOWN_CMD_ERR+a)}}function issueResolveLinks(a,d,b){"false"==d?executeCommonScript('$._ext.showConfirm("'+resourceBundle.RESOLVE_LINKS_LAYER_REORDER_ERR+'", "true", "'+resourceBundle.RESOLVE_LINKS_HEADER+'")',confirmResolveLinks,a,b):issueCommand(a,null,b)}function confirmResolveLinks(a,d,b){"true"==a&&issueCommand(d,null,b)}
function retrieveSettings(a,d,b){"true"===d?readUserSettings(updateProps,a,b):showAlert(resourceBundle.DOC_NOT_SAVED_ERR)}function preCommitHook(a,d,b){"true"==d?ZmPluginInst.host.preCommitHook(a,extractXMP,b):extractXMP(a,null,b)}function extractXMP(a,d,b){d&&(b?b.thumbpath=d:b={thumbpath:d});ZmPluginInst.host.extractXMP(a,getExtractedData,b)}
function getExtractedData(a,d,b){d&&(b?b.xmpFilePath=d:b={xmpFilePath:d});b&&b.enableLayerExtraction&&"true"==b.enableLayerExtraction?ZmPluginInst.host.getExtractedData(a,issueCommand,b):issueCommand(a,null,b)}function closeCurrentDocument(a,d,b){ZmPluginInst.host.closeActiveDocument(a,issueCommand,b)}function openFile(a){a.openPath&&ZmPluginInst.host.openFile(null,null,a)}
function issueCommand(a,d,b){var e=null;b||(b={});var f=!1;switch(a){case "update":case "revertdata":case "revertrenamed":case "revertmove":case "revertadd":case "revertall":case "smartCopy":var e=getFileToBeOpened,f=!0,c=new Date,c=c.getDate().toString()+(c.getMonth()+1).toString()+c.getFullYear().toString()+c.getHours().toString()+c.getMinutes().toString()+c.getSeconds().toString()+c.getMilliseconds().toString()+".txt";b.tmpfilename=c;break;case "import":e=getFileToBeOpened,c=new Date,c=c.getDate().toString()+
(c.getMonth()+1).toString()+c.getFullYear().toString()+c.getHours().toString()+c.getMinutes().toString()+c.getSeconds().toString()+c.getMilliseconds().toString()+".txt",b.tmpfilename=c;case "commit":case "quick_commit":case "quick_import":f=!0;d&&(b.epf=d);break;case "resolve-links":e=resolveLinks,f=!0,c=new Date,c=c.getDate().toString()+(c.getMonth()+1).toString()+c.getFullYear().toString()+c.getHours().toString()+c.getMinutes().toString()+c.getSeconds().toString()+c.getMilliseconds().toString()+
".txt",b.tmpfilename="relink_"+c}b.block=f;sendCommandRequest(getCommandParam(a,b),e)}function getFileToBeOpened(a){a&&a.tmpfilename&&executeCommonScript('$._ext.readTmpFile("'+a.tmpfilename.toString()+'", "'+a.remotepath+'", "'+a.modifiedFlag+'", "'+ZmPluginInst.host.hostAppCode+'")',null,null,null)}function resolveLinks(a){a&&a.tmpfilename&&ZmPluginInst.host.resolveLinks(null,null,a)}
function issueCommandNoRefresh(a,d,b){ZmPluginInst.host&&(!1===ZmPluginInst.host.isDefault&&d)&&issueCommand(a,null,{remotepath:d})}function getCommandParam(a,d){var b={cmdname:a,isPlugin:!0};if(d)for(var e in d)b[e]=d[e];return b};
