var CONFLICTED=function(){return{getStatus:function(){return"conflicted"},getStatusCode:function(){return 0}}}(),MODIFIED=function(){return{getStatus:function(){return"modified"},getStatusCode:function(){return 1}}}(),DELETED=function(){return{getStatus:function(){return"deleted"},getStatusCode:function(){return 2}}}(),READONLY=function(){return{getStatus:function(){return"read only"},getStatusCode:function(){return 3}}}(),LOCKED=function(){return{getStatus:function(){return"locked"},getStatusCode:function(){return 4}}}(),
ADDED=function(){return{getStatus:function(){return"added"},getStatusCode:function(){return 5}}}(),UPTO_DATE_NEEDED=function(){return{getStatus:function(){return"upto date needed"},getStatusCode:function(){return 6}}}(),RENAMED=function(){return{getStatus:function(){return"renamed"},getStatusCode:function(){return 7}}}(),NO_CHANGE=function(){return{getStatus:function(){return"no change"},getStatusCode:function(){return 8}}}(),UNVERSIONED=function(){return{getStatus:function(){return"unversioned"},
getStatusCode:function(){return 9}}}(),IGNORED=function(){return{getStatus:function(){return"ignored"},getStatusCode:function(){return 10}}}(),NON_WORKING_COPY=function(){return{getStatus:function(){return"non working copy"},getStatusCode:function(){return 11}}}(),MOVED=function(){return{getStatus:function(){return"moved"},getStatusCode:function(){return 12}}}(),VERSIONED=function(){return{getStatus:function(){return"versioned"},getStatusCode:function(){return 13}}}(),RESURRECTED=function(){return{getStatus:function(){return"resurrected"},
getStatusCode:function(){return 14}}}();function isNonWc(a){0>a&&(a*=-1);return a==NON_WORKING_COPY.getStatusCode()}function isWc(a){return!isNonWc(a)}function isUnVersioned(a){0>a&&(a*=-1);return a==UNVERSIONED.getStatusCode()||a==IGNORED.getStatusCode()}function isVersioned(a){0>a&&(a*=-1);return a<=NO_CHANGE.getStatusCode()||a>=MOVED.getStatusCode()}function isModified(a,b){if(!isVersioned(a))return!isVersioned(a);var c=isModifiedBit(b),d=isRenameorMoveBit(b);return c||d}
function isLockedBit(a){return 0!=(a&lockedMask)}function isModifiedBit(a){return 0!=(a&modifyMask)}function isRenameorMoveBit(a){return isRenamedBit(a)||isMoveBit(a)}function isRenamedBit(a){return 0!=(a&renameMask)}function isMoveBit(a){return 0!=(a&moveMask)}function refreshStatus(a){var b=a.code;a=a.bitset;0>b&&(b=-b);updateVersionStatus(b);updateLockStatus(b,a);updateModStatus(b,a);ZmPluginInst.host&&(ZmPluginInst.host.hostAppCode&&"AEFT"!==ZmPluginInst.host.hostAppCode)&&callTimer()}
function updateVersionStatus(a){isVersioned(a)?(jQuery("#iver").attr("src","./assets/green.png"),jQuery("#iver").attr("title",resourceBundle.IS_VER)):(jQuery("#iver").attr("src","./assets/red.png"),isNonWc(a)?jQuery("#iver").attr("title",resourceBundle.NOT_WC):jQuery("#iver").attr("title",resourceBundle.NOT_VER))}
function updateModStatus(a,b){if(isVersioned(a)){var c=isModifiedBit(b),d=isRenameorMoveBit(b);if(c||d){jQuery("#imod").attr("src","./assets/red.png");var e;e=c&&d?resourceBundle.IS_MOD_NAME:c?resourceBundle.IS_MOD:resourceBundle.IS_NAME;jQuery("#imod").attr("title",e)}else jQuery("#imod").attr("src","./assets/green.png"),jQuery("#imod").attr("title",resourceBundle.NOT_MOD);return c||d}jQuery("#imod").attr("src","./assets/red.png");jQuery("#imod").attr("title",resourceBundle.UNKNOWN_MOD)}
function updateLockStatus(a,b){isVersioned(a)?isLockedBit(b)?(jQuery("#ilock").attr("src","./assets/lock_small.png"),jQuery("#ilock").attr("title",resourceBundle.IS_LOCKED)):(jQuery("#ilock").attr("src","./assets/lock_open.png"),jQuery("#ilock").attr("title",resourceBundle.NOT_LOCKED)):(jQuery("#ilock").attr("src","./assets/orange.png"),jQuery("#ilock").attr("title",resourceBundle.UNKNOWN_LOCK))}
function refreshBlankFileStatus(){jQuery("#iver").attr("src","./assets/orange.png");jQuery("#imod").attr("src","./assets/orange.png");jQuery("#ilock").attr("src","./assets/orange.png");jQuery("#iver").attr("title",resourceBundle.VER_ICON_TOOLTIP);jQuery("#imod").attr("title",resourceBundle.MOD_ICON_TOOLTIP);jQuery("#ilock").attr("title",resourceBundle.LOCK_ICON_TOOLTIP);ZmPluginInst.host&&(ZmPluginInst.host.hostAppCode&&"AEFT"!==ZmPluginInst.host.hostAppCode)&&callTimer()}
var addMask=1,renameMask=2,moveMask=4,deleteMask=8,renameOrMoveMask=6,modifyMask=16,lockedMask=32,conflictMask=64;
