var TIMEOUT_ERROR_STR="ERROR: LAYER_TIMEOUT";function setCancelFlag(){executeCommonScript("$._ext.setLayerCancelFlag()",null,null,null)}function setUserDtls(b,a){if(b&&a){var c=b+"@"+a;gUserName=b;document.getElementById("settingsBtn").title=c;document.getElementById("userDtls").innerHTML=c}else gUserName=null,document.getElementById("settingsBtn").title="",document.getElementById("userDtls").innerHTML=""}
function updateLocaleTexts(b,a,c,d){document.getElementById("chkIntxt").innerHTML=resourceBundle.CHK_IN_LABEL;document.getElementById("quickChkInTxt").innerHTML=resourceBundle.QUICK_CHK_IN_LABEL;document.getElementById("lockUnlockTxt").innerHTML=resourceBundle.LOCK_UNLOCK_LABEL;document.getElementById("smartCpyTxt").innerHTML=resourceBundle.SMART_COPY_LABEL;document.getElementById("revertTxt").innerHTML=resourceBundle.REVERT_LABEL;document.getElementById("updateTxt").innerHTML=resourceBundle.UPDATE_LABEL;
document.getElementById("browserTxt").innerHTML=resourceBundle.BROWSE_LABEL;document.getElementById("taskManagerTxt").innerHTML=resourceBundle.WORKFLOW_LABEL;0<=c.indexOf("Mac")?document.getElementById("revealTxt").innerHTML=resourceBundle.REVEAL_LABEL_MAC:document.getElementById("revealTxt").innerHTML=resourceBundle.REVEAL_LABEL;document.getElementById("statTxt").innerHTML=resourceBundle.STAT_LABEL;document.getElementById("resolveLinkTxt").innerHTML=resourceBundle.RESOLVE_LINKS_LABEL;document.getElementById("getLockTxt").innerHTML=
resourceBundle.GET_LOCKS_LABEL;document.getElementById("releaseLockTxt").innerHTML=resourceBundle.RELEASE_LOCK_LABEL;document.getElementById("revChangeTxt").innerHTML=resourceBundle.REV_CHANGE_LABEL;document.getElementById("revRenamedTxt").innerHTML=resourceBundle.REV_RENAMED_LABEL;document.getElementById("revMovedTxt").innerHTML=resourceBundle.REV_MOVED_LABEL;document.getElementById("revAddedTxt").innerHTML=resourceBundle.REV_ADDED_LABEL;document.getElementById("revAllTxt").innerHTML=resourceBundle.REV_ALL_LABEL;
document.getElementById("settingsHdr").innerHTML=resourceBundle.USER_SETTINGS;document.getElementById("extractLyrTxt").innerHTML=resourceBundle.EXTRACT_LYR;document.getElementById("thumbTxt").innerHTML=resourceBundle.GENERATE_THUMB;document.getElementById("saveBtn").innerHTML=resourceBundle.SAVE;document.getElementById("cancelBtn").innerHTML=resourceBundle.CANCEL;document.getElementById("imod").title=resourceBundle.MOD_ICON_TOOLTIP;document.getElementById("ilock").title=resourceBundle.LOCK_ICON_TOOLTIP;
document.getElementById("iver").title=resourceBundle.VER_ICON_TOOLTIP;"AEFT"!=b?document.getElementById("refreshImg").title=resourceBundle.REFRESH_BTN_TOOLTIP+resourceBundle.AUTO_REFRESH_TOOLTIP:document.getElementById("refreshImg").title=resourceBundle.REFRESH_BTN_TOOLTIP;document.getElementById("chkinTd").title=resourceBundle.CHK_IN_TOOLTIP;document.getElementById("quickChkinTd").title=resourceBundle.QUICK_CHK_IN_TOOLTIP;document.getElementById("lockUnlockTd").title=resourceBundle.LOCK_UNLOCK_TOOLTIP;
document.getElementById("smartCopyTd").title=resourceBundle.SMART_COPY_TOOLTIP;document.getElementById("revertTd").title=resourceBundle.REVERT_TOOLTIP;document.getElementById("updateTd").title=resourceBundle.UPDATE_TOOLTIP;document.getElementById("browseTd").title=resourceBundle.BROWSE_TOOLTIP;document.getElementById("wfTd").title=resourceBundle.WORKFLOW_TOOLTIP;document.getElementById("rvlTd").title=resourceBundle.REVEAL_TOOLTIP;document.getElementById("statTd").title=resourceBundle.STAT_TOOLTIP;
document.getElementById("resolveLinks").title=resourceBundle.RESOLVE_LINKS_TOOLTIP;document.getElementById("searchInput").placeholder=resourceBundle.SEARCH_TXT;a&&0<=a.indexOf("es_")&&(jQuery("#browseDiv").css({"padding-bottom":"38.px"}),jQuery("#wfDiv").css({"padding-bottom":"38.px"}))}
function loadUI(){jQuery("#overlay").hide();jQuery("#resolveLinks").hide();jQuery("#getThumb").hide();jQuery("#thumbTxt").hide();var b=getHostApp();b&&("PHXS"===b||"PHSP"===b||"ILST"===b||"AEFT"===b||"IDSN"===b||"PPRO"===b)&&jQuery("#resolveLinks").show();if(b&&("AEFT"==b||"PPRO"==b))jQuery("#getThumb").show(),jQuery("#thumbTxt").show();jQuery(document).click(function(a){jQuery("#lockMenu").hide();jQuery("#revertMenu").hide();"lockDiv"===jQuery(a.target).closest("div").attr("id")?(a=jQuery("#lockDiv").position(),
jQuery("#lockMenu").css({top:Math.abs(a.top)+24+"px",left:Math.abs(a.left)+"px"}).show()):"revertDiv"===jQuery(a.target).closest("div").attr("id")?(a=jQuery("#revertDiv").position(),jQuery("#revertMenu").css({top:Math.abs(a.top)+24+"px",left:Math.abs(a.left)+"px"}).show()):"divBtn"===jQuery(a.target).closest("div").attr("class")&&launchCommand(jQuery(a.target).closest("div").attr("data-command"),"false")});jQuery(".hiddenMenu tr").click(function(a){launchCommand(jQuery(this).attr("id"),"false")});
jQuery(" #refreshBtn ").click(function(){launchCommand("refresh","true")});jQuery("#searchInput").keypress(function(a){"13"==(a.keyCode?a.keyCode:a.which)&&launchSearch()});jQuery(" #settingsBtn ").click(function(){launchCommand("loadSettings","true")});jQuery(" #cancelBtn ").click(function(){jQuery("#overlay").hide()});jQuery(" #saveBtn ").click(function(){launchCommand("saveSettings","true")});executeCommonScript("$._ext.getZoomProps()")};
