function ZmPluginInst(){var a=getHostApp(),b;switch(a){case "PHXS":case "PHSP":b=new ZmPhotoshop;b.hostAppCode=a;break;case "ILST":b=new ZmIllustrator;b.hostAppCode=a;break;case "IDSN":b=new ZmInDesign;b.hostAppCode=a;break;case "AEFT":b=new ZmAfterEffects;b.hostAppCode=a;break;case "PPRO":b=new ZmPremierPro;b.hostAppCode=a;break;default:b=new ZmPluginDefault,b.hostAppCode=a}return ZmPluginInst.host=b}function ZmPlugin(){}ZmPlugin.prototype.showInstance=function(){alert("ZmPLugin")};
ZmPlugin.prototype.getFilePath=function(a,b,c){executeScript('.getFilePath("'+c._isRefresh+'")',a,b,c)};ZmPlugin.prototype.saveDocument=function(a,b,c){executeScript(".saveDocument()",a,b,c)};ZmPlugin.prototype.preCommitHook=function(a,b,c){b(a,null,c)};ZmPlugin.prototype.getExtractedData=function(a,b,c){b(a,null,c)};ZmPlugin.prototype.extractXMP=function(a,b,c){b(a,null,c)};ZmPlugin.prototype.closeActiveDocument=function(a,b,c){executeScript(".closeActiveDocument()",a,b,c)};
ZmPlugin.prototype.openFile=function(a,b,c){c.openPath&&executeScript('.openFile("'+c.openPath+'")',a,b,c)};ZmPlugin.prototype.resolveLinks=function(a,b,c){executeScript('.resolveLinks("'+c.tmpfilename.toString()+'")',a,b,c)};ZmPlugin.prototype.isChangesSaved=function(a,b,c){};function ZmPhotoshop(){}ZmPhotoshop.prototype=new ZmPlugin;ZmPhotoshop.prototype.constructor=ZmPhotoshop;ZmPhotoshop.prototype.isDefault=!1;ZmPhotoshop.prototype.showInstance=function(){alert("ZmPhotoshop")};
ZmPhotoshop.prototype.getExtractedData=function(a,b,c){executeScript(".getExtractedData()",a,b,c)};ZmPhotoshop.prototype.saveDocument=function(a,b,c){var d=!1,e=!1;c&&(c.checkModified&&(d=c.checkModified),c.modifiedFlag&&(e=c.modifiedFlag));executeScript('.saveDocument("'+d+'", "'+e+'")',a,b,c)};ZmPhotoshop.prototype.isChangesSaved=function(a,b,c){executeScript(".isChangesSaved()",a,b,c)};function ZmIllustrator(){}ZmIllustrator.prototype=new ZmPlugin;ZmIllustrator.prototype.constructor=ZmIllustrator;
ZmIllustrator.prototype.isDefault=!1;ZmIllustrator.prototype.showInstance=function(){alert("ZmIllustrator")};ZmIllustrator.prototype.getExtractedData=function(a,b,c){executeScript(".getExtractedData()",a,b,c)};ZmIllustrator.prototype.isChangesSaved=function(a,b,c){executeScript(".isChangesSaved()",a,b,c)};function ZmInDesign(){}ZmInDesign.prototype=new ZmPlugin;ZmInDesign.prototype.constructor=ZmInDesign;ZmInDesign.prototype.isDefault=!1;ZmInDesign.prototype.showInstance=function(){alert("ZmInDesign")};
ZmInDesign.prototype.getExtractedData=function(a,b,c){executeScript(".getExtractedData()",a,b,c)};ZmInDesign.prototype.isChangesSaved=function(a,b,c){executeScript(".isChangesSaved()",a,b,c)};function ZmAfterEffects(){}ZmAfterEffects.prototype=new ZmPlugin;ZmAfterEffects.prototype.constructor=ZmAfterEffects;ZmAfterEffects.prototype.isDefault=!1;ZmAfterEffects.prototype.showInstance=function(){alert("ZmAfterEffects")};
ZmAfterEffects.prototype.preCommitHook=function(a,b,c){executeScript(".preCommitHook()",a,b,c)};ZmAfterEffects.prototype.getExtractedData=function(a,b,c){executeScript(".getExtractedData()",a,b,c)};ZmAfterEffects.prototype.extractXMP=function(a,b,c){executeScript(".extractXMP()",a,b,c)};ZmAfterEffects.prototype.isChangesSaved=function(a,b,c){executeScript(".isChangesSaved()",a,b,c)};function ZmPremierPro(){}ZmPremierPro.prototype=new ZmPlugin;ZmPremierPro.prototype.constructor=ZmPremierPro;
ZmPremierPro.prototype.isDefault=!1;ZmPremierPro.prototype.showInstance=function(){alert("ZmPremierPro")};ZmPremierPro.prototype.closeActiveDocument=function(a,b,c){b(a,null,c)};ZmPremierPro.prototype.preCommitHook=function(a,b,c){executeScript(".preCommitHook()",a,b,c)};ZmPremierPro.prototype.getExtractedData=function(a,b,c){executeScript(".getExtractedData()",a,b,c)};ZmPremierPro.prototype.isChangesSaved=function(a,b,c){executeScript(".isChangesSaved()",a,b,c)};function ZmPluginDefault(){}
ZmPluginDefault.prototype=new ZmPlugin;ZmPluginDefault.prototype.constructor=ZmPluginDefault;ZmPluginDefault.prototype.isDefault=!0;ZmPluginDefault.prototype.getFilePath=function(a){};function getHostApp(){return(new CSInterface).hostEnvironment.appName}function testInstance(){(new ZmPluginInst).showInstance()}function getThumb(a,b,c){a&&"TRUE"==a.toString().toUpperCase()?executeScript(".preCommitHook()",b,getExtractedData,c):getExtractedData(b,null,c)}
function executeScript(a,b,c,d){if(ZmPluginInst.host&&ZmPluginInst.host.hostAppCode){var e="$._ext_"+ZmPluginInst.host.hostAppCode+a;evalScript(e,function(a){try{var f=JSON.parse(a),g;if("true"===f.isSuccess){g=f.data;var h=f.linkedFileStr;h&&(d||(d={}),d.linkedFileStr=h);c&&c(b,g,d)}else a="",d&&(d._isRefresh&&"true"===d._isRefresh)&&c(b,null,d),f&&(a=f.error),a&&a.toString().toUpperCase()!=TIMEOUT_ERROR_STR?showAlert(resourceBundle.ACTION_NOT_COMPLETE+e+"\t"+resourceBundle.ERROR+a):a&&a.toString().toUpperCase()==
TIMEOUT_ERROR_STR&&c(b,null,d)}catch(k){showAlert(resourceBundle.SCRIPT_FAILURE+k.toString())}})}else showAlert(resourceBundle.INVALID_HOST)}function executeCommonScript(a,b,c,d){evalScript(a,function(a){b&&b(a,c,d)})};
